karser_robokassa_callback:
    path:  /robokassa/callback
    defaults: { _controller: KarserRobokassaBundle:Robokassa:callback }

karser_robokassa_success:
    path:  /robokassa/success
    defaults: { _controller: KarserRobokassaBundle:Robokassa:success }

karser_robokassa_fail:
    path:  /robokassa/fail
    defaults: { _controller: KarserRobokassaBundle:Robokassa:fail }
