fruitware_robokassa_callback:
    path:  /robokassa/callback
    defaults: { _controller: FruitwareRobokassaBundle:Robokassa:callback }

fruitware_robokassa_success:
    path:  /robokassa/success
    defaults: { _controller: FruitwareRobokassaBundle:Robokassa:success }

fruitware_robokassa_fail:
    path:  /robokassa/fail
    defaults: { _controller: FruitwareRobokassaBundle:Robokassa:fail }
